export const nigeriastates = [
  "abia",
  "abuja",
  "adamawa",
  "akwa_ibom",
  "anambra",
  "bauchi",
  "bayelsa",
  "benue",
  "borno",
  "cross_river",
  "delta",
  "ebonyi",
  "edo",
  "ekiti",
  "enugu",
  "gombe",
  "imo",
  "jigawa",
  "kaduna",
  "kano",
  "katsina",
  "kebbi",
  "kogi",
  "kwara",
  "lagos",
  "nasarawa",
  "niger",
  "ogun",
  "ondo",
  "osun",
  "oyo",
  "plateau",
  "rivers",
  "sokoto",
  "taraba",
  "yobe",
  "zamfara",
];
export const stateslgs = {
  abia: [
    "Aba North",
    "Aba South",
    "Arochukwu",
    "Bende",
    "Ikwuano",
    "Isiala Ngwa",
    "Isuikwuato",
    "Obi Ngwa",
    "Ohafia",
    "Osisioma Ngwa",
    "Ugwunagbo",
    "Ukwa",
    "Umu Nneochi",
    "Umuahia",
  ],
  abuja: [
    "Abaji",
    "Apo District",
    "Asokoro",
    "Bwari",
    "Central Business District",
    "Dakibiyu",
    "Dakwo District",
    "Dei-Dei",
    "Duboyi",
    "Durumi",
    "Dutse-Alhaji",
    "Gaduwa",
    "Galadimawa",
    "Garki 1",
    "Garki 2",
    "Gudu",
    "Guzape District",
    "Gwagwa",
    "Gwagwalada",
    "Gwarinpa",
    "Idu Industrial",
    "Jabi",
    "Jahi",
    "Jikwoyi",
    "Jiwa",
    "Kabusa",
    "Kado",
    "Karmo",
    "Karshi",
    "Karu",
    "Katampe",
    "Kaura",
    "Kpeyegyi",
    "Kubwa",
    "Kuchigoro",
    "Kuje",
    "Kurudu",
    "Kwali",
    "Lokogoma",
    "Lugbe District",
    "Mabushi",
    "Maitama",
    "Mararaba",
    "Masaka",
    "Mbora",
    "Mpape",
    "Nyanya",
    "Okanje",
    "Orozo",
    "Pyakasa",
    "Sabo Gida",
    "Utako",
    "Wumba",
    "Wuse",
    "Wuse 2",
    "Wuye",
    "Zuba",
  ],
  adamawa: [
    "Demsa",
    "Fufore",
    "Ganye",
    "Girei",
    "Gombi",
    "Guyuk",
    "Hong",
    "Jada",
    "Lamurde",
    "Madagali",
    "Maiha",
    "Mayo-Belwa",
    "Michika",
    "Mubi North",
    "Mubi South",
    "Numan",
    "Shelleng",
    "Song",
    "Toungo",
    "Yola North",
    "Yola South",
  ],
  akwa_ibom: [
    "Abak",
    "Eastern Obolo",
    "Esit-Eket",
    "Essien Udim",
    "Etim-Ekpo",
    "Etinan",
    "Ibeno",
    "Ibesikpo Asutan",
    "Ibiono Ibom",
    "Ika",
    "Ikono",
    "Ikot Abasi",
    "Ikot Ekpene",
    "Ini",
    "Itu",
    "Mbo",
    "Mkpat Enin",
    "Nsit Atai",
    "Nsit Ibom",
    "Nsit Ubium",
    "Obot Akara",
    "Okobo",
    "Onna",
    "Oron",
    "Oruk Anam",
    "Udung Uko",
    "Ukanafun",
    "Uquo-Ibeno",
    "Uruan",
    "Urue-Offong/Oruko",
    "Uyo",
  ],
  anambra: [
    "Aghamelu",
    "Aguata",
    "Anambra East",
    "Anambra West",
    "Anaocha",
    "Awka",
    "Ayamelum",
    "Dunukofia",
    "Ekwusigo",
    "Idemili",
    "Ihiala",
    "Njikoka",
    "Nnewi",
    "Ogbaru",
    "Onitsha",
    "Orumba",
  ],
  bauchi: [
    "Alkaleri",
    "Bauchi LGA",
    "Bogoro",
    "Damban",
    "Darazo",
    "Dass",
    "Gamawa",
    "Ganjuwa",
    "Giade",
    "Itas/Gadau",
    "Jama are",
    "Katagum",
    "Kirfi",
    "Misau",
    "Ningi",
    "Shira",
    "Toro",
    "Warji",
    "Zaki",
  ],
  bayelsa: [
    "Brass",
    "Ekeremor",
    "Kolokuma/Opokuma",
    "Nembe",
    "Ogbia",
    "Sagbama",
    "Southern Ijaw",
    "Yenagoa",
  ],
  benue: [
    "Ado",
    "Agatu",
    "Apa",
    "Buruku",
    "Gboko",
    "Guma",
    "Gwer",
    "Katsina-Ala",
    "Konshisha",
    "Kwande",
    "Logo",
    "Makurdi",
    "Obi",
    "Ogbadibo",
    "Ohimini",
    "Oju",
    "Okpokwu",
    "Otukpo",
    "Tarka",
    "Ukum",
    "Ushongo",
    "Vandeikya",
  ],
  borno: [
    "Abadam",
    "Askira/Uba",
    "Bama",
    "Bayo",
    "Biu",
    "Chibok",
    "Damboa",
    "Dikwa",
    "Gubio",
    "Guzamala",
    "Gwoza",
    "Hawul",
    "Jere",
    "Kaga",
    "Kala/Balge",
    "Konduga",
    "Kukawa",
    "Kwaya Kusar",
    "Mafa",
    "Magumeri",
    "Maiduguri",
    "Marte",
    "Mobbar",
    "Monguno",
    "Ngala",
    "Nganzai",
    "Shani",
  ],
  cross_river: [
    "Abi",
    "Akamkpa",
    "Akpabuyo",
    "Bakassi",
    "Bekwara",
    "Biase",
    "Boki",
    "Calabar",
    "Etung",
    "Ikom",
    "Obanliku",
    "Obubra",
    "Obudu",
    "Odukpani",
    "Ogoja",
    "Yakuur",
    "Yala",
  ],
  delta: [
    "Aniocha North",
    "Aniocha South",
    "Bomadi",
    "Burutu",
    "Ethiope East",
    "Ethiope West",
    "Ika North East",
    "Ika South",
    "Isoko",
    "Ndokwa East",
    "Ndokwa West",
    "Okpe",
    "Oshimili North",
    "Oshimili South",
    "Patani",
    "Sapele",
    "Udu",
    "Ugheli",
    "Uvwie",
    "Warri",
  ],
  ebonyi: [
    "Abakaliki",
    "Afikpo North",
    "Afikpo South",
    "Ebonyi",
    "Ezza",
    "Ikwo",
    "Ishielu",
    "Ivo",
    "Izzi",
    "Ohaozara",
    "Ohaukwu",
    "Onicha",
  ],
  edo: [
    "Akoko-Edo",
    "Auchi",
    "Benin City",
    "Egor",
    "Ekpoma",
    "Esan North East",
    "Fugar",
    "Igueben",
    "Ikpoba-Okha",
    "Irrua",
    "Okada",
    "Orhionmwon",
    "Ovia South",
    "Owan",
    "Ubiaja",
    "Uhunmwonde",
  ],
  ekiti: [
    "Ado Ekiti",
    "Aiyekire (Gbonyin)",
    "Aramoko",
    "Efon",
    "Emure",
    "Ido-Osi",
    "Ijero",
    "Ikere",
    "Ikole",
    "Ilawe",
    "Ilejemeje",
    "Irepodun/Ifelodun",
    "Ise/Orun",
    "Moba",
    "Omuo",
    "Oye",
  ],
  enugu: [
    "Aninri",
    "Awgu",
    "Enugu",
    "Ezeagu",
    "Igbo Eze South",
    "Igbo-Etiti",
    "Igbo-Eze North",
    "Isi-Uzo",
    "Nkanu East",
    "Nkanu West",
    "Nsukka",
    "Oji-River",
    "Udenu",
    "Udi",
    "Uzo-Uwani",
  ],
  gombe: [
    "Akko",
    "Balanga",
    "Billiri",
    "Dukku",
    "Funakaye",
    "Gombe LGA",
    "Kaltungo",
    "Kwami",
    "Nafada",
    "Shomgom",
    "Yamaltu/Deba",
  ],
  imo: [
    "Aboh-Mbaise",
    "Ahiazu-Mbaise",
    "Ehime-Mbano",
    "Ezinihitte",
    "Ezinihitte Mbaise",
    "Ideato North",
    "Ideato South",
    "Ihitte/Uboma",
    "Ikeduru",
    "Isiala Mbano",
    "Isu",
    "Mbaitoli",
    "Ngor-Okpala",
    "Njaba",
    "Nkwerre",
    "Nwangele",
    "Obowo",
    "Oguta",
    "Ohaji/Egbema",
    "Okigwe",
    "Onuimo",
    "Orlu",
    "Orsu",
    "Oru",
    "Owerri",
  ],
  jigawa: [
    "Auyo",
    "Babura",
    "Biriniwa",
    "Buji",
    "Dutse-Jigawa",
    "Gagarawa",
    "Garki",
    "Gumel",
    "Guri",
    "Gwaram",
    "Gwiwa",
    "Hadejia",
    "Jahun",
    "Kafin Hausa",
    "Kaugama",
    "Kazaure",
    "Kiri Kasamma",
    "Kiyawa",
    "Maigatari",
    "Malam Madori",
    "Miga",
    "Ringim",
    "Roni",
    "Sule-Tankarkar",
    "Taura",
    "Yankwashi",
  ],
  kaduna: [
    "Birnin-Gwari",
    "Chikun",
    "Giwa",
    "Igabi",
    "Ikara",
    "Jaba",
    "Jema a",
    "Kachia",
    "Kaduna / Kaduna State",
    "Kagarko",
    "Kajuru",
    "Kaura-Kaduna",
    "Kauru",
    "Kubau",
    "Kudan",
    "Lere",
    "Makarfi",
    "Sanga",
    "Soba",
    "Zango-Kataf",
    "Zaria",
  ],
  kano: [
    "Ajingi",
    "Albasu",
    "Bagwai",
    "Bebeji",
    "Bichi",
    "Bunkure",
    "Dala",
    "Dambatta",
    "Dawakin Kudu",
    "Dawakin Tofa",
    "Doguwa",
    "Fagge",
    "Gabasawa",
    "Garko",
    "Garum Mallam",
    "Garun Mallam",
    "Gaya",
    "Gezawa",
    "Gwale",
    "Gwarzo",
    "Kabo",
    "Kano Municipal",
    "Karaye",
    "Kibiya",
    "Kiru",
    "Kumbotso",
    "Kunchi",
    "Kura",
    "Madobi",
    "Makoda",
    "Minjibir",
    "Nasarawa-Kano",
    "Rano",
    "Rimin Gado",
    "Rogo",
    "Shanono",
    "Sumaila",
    "Takai",
    "Tarauni",
    "Tofa",
    "Tsanyawa",
    "Tudun Wada",
    "Ungogo",
    "Warawa",
    "Wudil",
  ],
  katsina: [
    "Bakori",
    "Batagarawa",
    "Batsari",
    "Baure",
    "Bindawa",
    "Charanchi",
    "Dan Musa",
    "Dandume",
    "Danja",
    "Daura",
    "Dutsi",
    "Dutsin-Ma",
    "Faskari",
    "Funtua",
    "Ingawa",
    "Jibia",
    "Kafur",
    "Kaita",
    "Kankara",
    "Kankia",
    "Katsina",
    "Kurfi",
    "Kusada",
    "Mai adua",
    "Malumfashi",
    "Mani",
    "Mashi",
    "Matazu",
    "Musawa",
    "Rimi",
    "Sabuwa",
    "Safana",
    "Sandamu",
    "Zango",
  ],
  kebbi: [
    "Aleiro",
    "Arewa-Dandi",
    "Argungu",
    "Augie",
    "Bagudo",
    "Birnin Kebbi",
    "Bunza",
    "Dandi",
    "Fakai",
    "Gwandu",
    "Jega",
    "Kalgo",
    "Koko/Besse",
    "Maiyama",
    "Ngaski",
    "Sakaba",
    "Shanga",
    "Suru",
    "Wasagu/Danko",
    "Yauri",
    "Zuru",
  ],
  kogi: [
    "Adavi",
    "Ajaokuta",
    "Ankpa",
    "Bassa",
    "Dekina",
    "Ibaji",
    "Idah",
    "Igala Mela",
    "Igalamela-Odolu",
    "Ijumu",
    "Kabba/Bunu",
    "Kogi LGA",
    "Koton Karfe",
    "Lokoja",
    "Mopa-Muro",
    "Ofu",
    "Ogori/Magongo",
    "Okehi",
    "Okene",
    "Olamaboro",
    "Omala",
    "Yagba East",
    "Yagba West",
  ],
  kwara: [
    "Asa",
    "Baruten",
    "Edu",
    "Ekiti-Kwara",
    "Ifelodun-Kwara",
    "Ilorin East",
    "Ilorin South",
    "Ilorin West",
    "Irepodun-Kwara",
    "Isin",
    "Kaiama",
    "Moro",
    "Oke-Ero",
    "Oyun",
    "Pategi",
  ],
  lagos: [
    "Abule Egba",
    "Agbara-Igbesan",
    "Agboyi/Ketu",
    "Agege",
    "Ajah",
    "Alimosho",
    "Amuwo-Odofin",
    "Badagry",
    "Egbe Idimu",
    "Ejigbo",
    "Eko Atlantic",
    "Epe",
    "Gbagada",
    "Ibeju",
    "Ifako-Ijaiye",
    "Ikeja",
    "Ikorodu",
    "Ikotun/Igando",
    "Ikoyi",
    "Ilashe",
    "Ilupeju",
    "Ipaja",
    "Isolo",
    "Kosofe",
    "Lagos Island (Eko)",
    "Lekki",
    "Magodo",
    "Maryland",
    "Mushin",
    "Ogba",
    "Ogudu",
    "Ojo",
    "Ojodu",
    "Ojota",
    "Orile",
    "Oshodi",
    "Shomolu",
    "Surulere",
    "Tarkwa Bay Island",
    "Victoria Island",
    "Yaba",
  ],
  nasarawa: [
    "Akwanga",
    "Awe",
    "Doma",
    "Karu-Nasarawa",
    "Keana",
    "Keffi",
    "Kokona",
    "Lafia",
    "Nasarawa",
    "Nasarawa-Eggon",
    "Obi-Nasarawa",
    "Toto",
  ],
  niger: [
    "Agaie",
    "Agwara",
    "Bida",
    "Borgu",
    "Bosso",
    "Chanchaga",
    "Edati",
    "Gbako",
    "Gurara",
    "Kontagora",
    "Lapai",
    "Lavun",
    "Magama",
    "Mariga",
    "Mashegu",
    "Minna",
    "Mokwa",
    "Muya",
    "Paikoro",
    "Rafi",
    "Rijau",
    "Shiroro",
    "Suleja",
    "Tafa",
    "Wushishi",
  ],
  ogun: [
    "Abeokuta North",
    "Abeokuta South",
    "Ado-Odo/Ota",
    "Ayetoro",
    "Ewekoro",
    "Ifo",
    "Ijebu",
    "Ijebu Ode",
    "Ikenne",
    "Ilaro",
    "Imeko Afon",
    "Ipokia",
    "Obafemi-Owode",
    "Odeda",
    "Odogbolu",
    "Ogun Waterside",
    "Remo North",
    "Sagamu",
  ],
  ondo: [
    "Akungba",
    "Akure",
    "Ese-Odo",
    "Idanre",
    "Ifedore",
    "Iju/Itaogbolu",
    "Ikare Akoko",
    "Ilaje",
    "Ile-Oluji-Okeigbo",
    "Irele",
    "Isua",
    "Odigbo",
    "Oka",
    "Okeagbe",
    "Okeigbo",
    "Okitipupa",
    "Ondo / Ondo State",
    "Ose",
    "Owo",
  ],
  osun: [
    "Aiyedade",
    "Aiyedire",
    "Atakumosa East",
    "Atakumosa West",
    "Boluwaduro",
    "Ede",
    "Egbedore",
    "Ife",
    "Ifedayo",
    "Ifelodun-Osun",
    "Ila",
    "Ilesa",
    "Irepodun-Osun",
    "Irewole",
    "Isokan",
    "Iwo",
    "Obokun",
    "Ola-Oluwa",
    "Olorunda-Osun",
    "Oriade",
    "Orolu",
    "Osogbo",
  ],
  oyo: [
    "Afijio",
    "Akinyele",
    "Atiba",
    "Atisbo",
    "Ayete",
    "Egbeda",
    "Eruwa",
    "Ibadan",
    "Ido",
    "Igbo Ora",
    "Irepo",
    "Iseyin",
    "Itesiwaju",
    "Iwajowa",
    "Kajola",
    "Lagelu",
    "Ogbomosho North",
    "Ogbomosho South",
    "Ogo Oluwa",
    "Olorunsogo",
    "Oluyole",
    "Ona-Ara",
    "Orelope",
    "Ori Ire",
    "Oyo",
    "Saki East",
    "Saki West",
    "Surulere-Oyo",
  ],
  plateau: [
    "Barkin Ladi",
    "Bassa-Plateau",
    "Bokkos",
    "Jos",
    "Kanam",
    "Kanke",
    "Langtang North",
    "Langtang South",
    "Mangu",
    "Mikang",
    "Pankshin",
    "Quaan Pan",
    "Riyom",
    "Shendam",
    "Wase",
  ],
  rivers: [
    "Abua/Odual",
    "Ahoada",
    "Akuku Toru",
    "Andoni",
    "Asari-Toru",
    "Bonny",
    "Degema",
    "Eleme",
    "Emohua",
    "Etche",
    "Gokana",
    "Ikwerre",
    "Khana",
    "Obio-Akpor",
    "Ogba/Egbema/Ndoni",
    "Ogu/Bolo",
    "Okrika",
    "Omuma",
    "Oyigbo",
    "Port-Harcourt",
    "Tai",
  ],
  sokoto: [
    "Binji",
    "Bodinga",
    "Dange-Shuni",
    "Gada",
    "Goronyo",
    "Gudu LGA",
    "Gwadabawa",
    "Illela",
    "Isa",
    "Kebbe",
    "Kware",
    "Rabah",
    "Sabon Birni",
    "Shagari",
    "Silame",
    "Sokoto North",
    "Sokoto South",
    "Tambuwal",
    "Tangaza",
    "Tureta",
    "Wamako",
    "Wurno",
    "Yabo",
  ],
  taraba: [
    "Ardo-Kola",
    "Bali",
    "Donga",
    "Gashaka",
    "Gassol",
    "Ibi",
    "Jalingo",
    "Karim-Lamido",
    "Kurmi",
    "Lau",
    "Sardauna",
    "Takum",
    "Ussa",
    "Wukari",
    "Yorro",
    "Zing",
  ],
  yobe: [
    "Bade",
    "Bursari",
    "Damaturu",
    "Fika",
    "Fune",
    "Geidam",
    "Gujba",
    "Gulani",
    "Jakusko",
    "Karasuwa",
    "Machina",
    "Nangere",
    "Nguru",
    "Potiskum",
    "Tarmua",
    "Yunusari",
    "Yusufari",
  ],
  zamfara: [
    "Anka",
    "Bakura",
    "Birnin Magaji",
    "Bukkuyum",
    "Bungudu",
    "Gummi",
    "Gusau",
    "Kaura Namoda",
    "Maradun",
    "Maru",
    "Shinkafi",
    "Talata Mafara",
    "Tsafe",
    "Zurmi",
  ],
};
